lib/my_blog_web/router.ex
defmodule MyBlogWeb.Router do
  use MyBlogWeb, :router

  import MyBlogWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MyBlogWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MyBlogWeb do
    pipe_through :browser

    live "/", IndexLive
    live "/blog", BlogLive
    live "/tags", TagLive
    live "/tags/:name", TaggedArticle
    live "/projects", ProjectLive
    live "/about", AboutLive
    live "/blog/:slug", DetailsLive

    live_session :admin, on_mount: {MyBlogWeb.LiveAuth, :admin} do
      live "/articles", ArticleLive
      live "/articles/new", ArticleFormLive
      live "/articles/:id/edit", ArticleFormLive
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyBlogWeb do
  #   pipe_through :api
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", MyBlogWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", MyBlogWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", MyBlogWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update

    get "/*path", PageController, :not_found
  end
end

lib/my_blog_web/controllers/user_registration_controller.ex
defmodule MyBlogWeb.UserRegistrationController do
  use MyBlogWeb, :controller

  alias MyBlog.Account
  alias MyBlog.Account.User
  alias MyBlogWeb.UserAuth

  def new(conn, _params) do
    changeset = Account.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Account.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Account.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/my_blog_web/views/user_registration_view.ex
defmodule MyBlogWeb.UserRegistrationView do
  use MyBlogWeb, :view
end

lib/my_blog_web/templates/user_registration/new.html.heex
<section class="bg-[#F4F7FF] py-20 lg:py-[120px]">
      <div class="flex flex-wrap -mx-4">
         <div class="w-full px-4">
            <div
               class="
               max-w-[525px]
               mx-auto
               text-center
               bg-white
               rounded-lg
               relative
               overflow-hidden
               py-16
               px-10
               sm:px-12
               md:px-[60px]
               "
               >
               <div class="mb-5 md:mb-10 text-center">
                  <h3 class="text-4xl text-gray-700">Register</h3>
               </div>
               <.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
                  <%= if @changeset.action do %>
                    <div class="alert alert-danger">
                      <p>Oops, something went wrong! Please check the errors below.</p>
                    </div>
                  <% end %>
                  <div class="mb-6">
                     <%= email_input f, :email, required: true, placeholder: "Email", 
                        class: "
                        w-full
                        rounded-md
                        border
                        bordder-[#E9EDF4]
                        py-3
                        px-5
                        bg-[#FCFDFE]
                        text-base text-body-color
                        placeholder-[#ACB6BE]
                        outline-none
                        focus-visible:shadow-none
                        focus:border-primary
                        "
                        %>
                  </div>
                  <div class="flex items-center mb-4">
                    <%= error_tag f, :email %>
                  </div>
                  <div class="mb-6">
                     <%= password_input f, :password, required: true, placeholder: "Password",
                        class: "
                        w-full
                        rounded-md
                        border
                        bordder-[#E9EDF4]
                        py-3
                        px-5
                        bg-[#FCFDFE]
                        text-base text-body-color
                        placeholder-[#ACB6BE]
                        outline-none
                        focus-visible:shadow-none
                        focus:border-primary
                        "
                        %>
                  </div>
                  <div class="flex items-center mb-4">
                    <%= error_tag f, :password %>
                  </div>
                  
                  <div class="mb-10">
                     <button
                        class="
                        w-full
                        rounded-md
                        border
                        border-primary
                        py-3
                        px-5
                        bg-blue-600
                        text-base text-white
                        cursor-pointer
                        hover:bg-opacity-90
                        transition
                        "
                        >Register</button>
                  </div>
               </.form>
               
               <%= link "Forget Password?", to: Routes.user_reset_password_path(@conn, :new),
                  class: "
                  text-base
                  inline-block
                  mb-2
                  text-[#adadad]
                  hover:underline hover:text-primary
                  "
                  %>
               
               
               <p class="text-base text-[#adadad]">
                  Already a member?
                  <%= link "Sign In", to: Routes.user_session_path(@conn, :new), class: "text-blue-600 hover:underline" %>
               </p>
               <div>
               </div>
            </div>
         </div>
      </div>
</section>
<!-- ====== Forms Section End -->